version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/database:/app/database
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

